#   Main Configs   #

baseurl: 
url: http://dingtim.github.io
date_format: "ordinal"
title: 吃饱等饿
subtitle: "学习改变命运"
description: "吃饱等饿"
keywords: dingtim
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Ding tim
organization: DNA, Inc.
organization_url: https://www.cpsdna.com
github_username: dingtim
location: Nanjing, China
email: dingtim@gmail.com
# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: dingtim/dingtim.github.io
# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus
comments_provider: disqus

# !!!重要!!! 请修改下面这些用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
disqus_username: dingtim

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1
