# Basic
title: 吃饱等饿
subtitle: 深度学习
welcome_message: <a href="https://github.com/dingtim/docker-library" target="_blank">欢迎</a>
description: 来自互联网.
creator: <a href="http://dingtim.github.io">@dingtim/a>

url: "http://dingtim.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 吃饱等饿的博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我的项目, url: 'http://dingtim.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
